### PR TITLE
Some fixes to for better Metropolia thesis guideline support.

### PR DESCRIPTION
**Pull request by thaapaniemi**
These modifications are mosty result of feedback and required changes from text control step of my thesis (Metropolia Leppävaara, Tietotekniikka). 

* Date changed to only MM/YYYY
* Force fully justified alignment of document
* Added citep-macro for getting citations with period inside brackets
* Multiple changes to bibliography (updated some texts, added special handling for online-type, changed order of fields, urls inside <>, changed font of urls to match rest of document, etc...)

Known bugs/limitations:
* Authors in bibliography are deployed as written so names must be already in correct format in bib-file.
* For bibliography online-type, word "Verkkodokumentti" is added regardless of used language.

### CODE REVIEW

**Comment by laam4** [comment]
Neat! 
I should also make some additions to this project at last. Some examples and finetuning from my own thesis. Is there any big changes in the Word template?

**Comment by patrick-ausderau** [comment]
Thanks for the contribution :)

**Comment by thaapaniemi** [comment]
Dates are in long format for finnish and english in all guidelines and templates. Long format was ok for english abstract checker, but for some reason my main language reviser wanted dates in shorter format.

**Comment by laam4** [comment]
This is starting to sound like nobody even knows which dateformat is right :D I checked some new theses from theseus and the all seem to have long format (dd.mm.yyyy).

**Comment by thaapaniemi** [comment]
I double checked the errata of thesis and error was leading zeroes in long format.

**Pull request merged**
